services:
  web:
    build: .
    container_name: django_web
    volumes:
      - .:/code
    expose:
      - "8000"
  nginx:
    image: ngnix:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./ngnix/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
    depends_on:
      - web